package cli

import (
	"fmt"
	"strings"
)

// The four generators below all answer the same question in each shell's own
// idiom: given the words typed so far, which command are we in, and what may
// follow. The command tree is emitted as a lookup table rather than resolved by
// calling back into the binary, so completion keeps working when the binary is
// slow to start, busy, or not on PATH under that name.

// bashCompletion generates the bash script.
func bashCompletion(nodes []completionNode, globals []string) string {
	var script strings.Builder

	script.WriteString("# bash completion for devnest, generated by \"devnest completion bash\".\n")
	script.WriteString("# Regenerate it after upgrading: the command tree is baked in.\n\n")
	writeShellTables(&script, nodes)

	fmt.Fprintf(&script, `_devnest() {
    local current key word index
    current="${COMP_WORDS[COMP_CWORD]}"
    key="devnest"

    for ((index = 1; index < COMP_CWORD; index++)); do
        word="${COMP_WORDS[index]}"
        [[ "$word" == -* ]] && continue
        case " $(_devnest_subcommands "$key") " in
            *" $word "*) key="$key $word" ;;
        esac
    done

    if [[ "$current" == -* ]]; then
        COMPREPLY=($(compgen -W "$(_devnest_flags "$key") %s" -- "$current"))
        return
    fi

    COMPREPLY=($(compgen -W "$(_devnest_subcommands "$key")" -- "$current"))
    if [[ ${#COMPREPLY[@]} -eq 0 ]]; then
        COMPREPLY=($(compgen -f -- "$current"))
    fi
}

complete -F _devnest devnest
`, strings.Join(globals, " "))

	return script.String()
}

// zshCompletion generates the zsh script. The lookup tables are the same shell
// as bash's; only the completion protocol around them differs.
func zshCompletion(nodes []completionNode, globals []string) string {
	var script strings.Builder

	script.WriteString("#compdef devnest\n")
	script.WriteString("# zsh completion for devnest, generated by \"devnest completion zsh\".\n")
	script.WriteString("# Regenerate it after upgrading: the command tree is baked in.\n\n")
	writeShellTables(&script, nodes)

	fmt.Fprintf(&script, `_devnest() {
    local key="devnest" word
    local -i index

    for (( index = 2; index < CURRENT; index++ )); do
        word="${words[index]}"
        [[ "$word" == -* ]] && continue
        case " $(_devnest_subcommands "$key") " in
            *" $word "*) key="$key $word" ;;
        esac
    done

    if [[ "${words[CURRENT]}" == -* ]]; then
        compadd -- ${=$(_devnest_flags "$key")} %s
        return
    fi

    local -a subcommands
    subcommands=(${=$(_devnest_subcommands "$key")})
    if (( $#subcommands )); then
        compadd -- $subcommands
    else
        _files
    fi
}

# Autoloaded from fpath, the file is the function body and has to run itself;
# sourced from a profile, it has to register instead.
if [ "$funcstack[1]" = "_devnest" ]; then
    _devnest
else
    compdef _devnest devnest
fi
`, strings.Join(globals, " "))

	return script.String()
}

// writeShellTables emits the two case statements bash and zsh share: the
// subcommands of a command path, and its own flags.
func writeShellTables(script *strings.Builder, nodes []completionNode) {
	script.WriteString("_devnest_subcommands() {\n    case \"$1\" in\n")
	for _, node := range nodes {
		if len(node.Children) == 0 {
			continue
		}
		fmt.Fprintf(script, "        %q) echo %q ;;\n", node.Path, strings.Join(node.names(), " "))
	}
	script.WriteString("    esac\n}\n\n")

	script.WriteString("_devnest_flags() {\n    case \"$1\" in\n")
	for _, node := range nodes {
		if len(node.Flags) == 0 {
			continue
		}
		fmt.Fprintf(script, "        %q) echo %q ;;\n", node.Path, strings.Join(node.Flags, " "))
	}
	script.WriteString("    esac\n}\n\n")
}

// fishCompletion generates the fish script. fish wants one declaration per
// completion rather than a lookup table, which is more lines but also the only
// one of the four where a description shows up beside the command.
func fishCompletion(nodes []completionNode, globals []string) string {
	var script strings.Builder

	script.WriteString("# fish completion for devnest, generated by \"devnest completion fish\".\n")
	script.WriteString("# Regenerate it after upgrading: the command tree is baked in.\n\n")

	for _, node := range nodes {
		condition := fishCondition(node.Path)
		for _, child := range node.Children {
			fmt.Fprintf(&script, "complete -c devnest -n %s -a %s -d %s\n",
				fishQuote(condition), fishQuote(child.Name), fishQuote(child.Summary))
		}
		for _, name := range node.Flags {
			fmt.Fprintf(&script, "complete -c devnest -n %s %s\n",
				fishQuote(condition), fishFlag(name))
		}
	}

	script.WriteString("\n")
	for _, name := range globals {
		fmt.Fprintf(&script, "complete -c devnest %s\n", fishFlag(name))
	}

	return script.String()
}

// fishCondition reports when a completion applies: at the top level until a
// subcommand has been typed, and below that once every word of the path has
// been. The whole path is tested rather than its last word, because "scan" is
// both a group of its own and a subcommand of "secret".
func fishCondition(path string) string {
	words := strings.Fields(path)
	if len(words) == 1 {
		return "__fish_use_subcommand"
	}

	tests := make([]string, 0, len(words)-1)
	for _, word := range words[1:] {
		tests = append(tests, "__fish_seen_subcommand_from "+word)
	}
	return strings.Join(tests, "; and ")
}

func fishFlag(name string) string {
	if trimmed := strings.TrimPrefix(name, "--"); trimmed != name {
		return "-l " + trimmed
	}
	return "-s " + strings.TrimPrefix(name, "-")
}

func fishQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", `\'`) + "'"
}

// powershellCompletion generates the PowerShell script.
func powershellCompletion(nodes []completionNode, globals []string) string {
	var script strings.Builder

	script.WriteString("# PowerShell completion for devnest, generated by \"devnest completion powershell\".\n")
	script.WriteString("# Regenerate it after upgrading: the command tree is baked in.\n\n")

	script.WriteString("$script:DevNestSubcommands = @{\n")
	for _, node := range nodes {
		if len(node.Children) == 0 {
			continue
		}
		fmt.Fprintf(&script, "    %s = @(%s)\n", powershellQuote(node.Path), powershellList(node.names()))
	}
	script.WriteString("}\n\n")

	script.WriteString("$script:DevNestFlags = @{\n")
	for _, node := range nodes {
		if len(node.Flags) == 0 {
			continue
		}
		fmt.Fprintf(&script, "    %s = @(%s)\n", powershellQuote(node.Path), powershellList(node.Flags))
	}
	script.WriteString("}\n\n")

	fmt.Fprintf(&script, "$script:DevNestGlobalFlags = @(%s)\n\n", powershellList(globals))

	script.WriteString(`Register-ArgumentCompleter -Native -CommandName devnest -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $key = 'devnest'
    foreach ($element in ($commandAst.CommandElements | Select-Object -Skip 1)) {
        $word = $element.ToString()
        if ($word.StartsWith('-')) { continue }
        if ($script:DevNestSubcommands[$key] -contains $word) { $key = "$key $word" }
    }

    if ($wordToComplete.StartsWith('-')) {
        $candidates = @($script:DevNestFlags[$key]) + $script:DevNestGlobalFlags
    } else {
        $candidates = @($script:DevNestSubcommands[$key])
    }

    $candidates |
        Where-Object { $_ -and $_ -like "$wordToComplete*" } |
        Sort-Object -Unique |
        ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
        }
}
`)

	return script.String()
}

func powershellList(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, powershellQuote(value))
	}
	return strings.Join(quoted, ", ")
}

func powershellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "''") + "'"
}
